### ISSUE TITLE
Download Babi data

### ISSUE THREAD

**Issue by lyt91222** [yujiali/ggnn#1]
Hi, I have a problem when downloading babi data using 'bash get_10_fold_data.sh'. The error is shown as 
![screen shot 2016-07-02 at 8 18 18 pm](https://cloud.githubusercontent.com/assets/19891253/16543077/4331ea04-4092-11e6-941d-744b319581e0.png)

I encounter the same problem at different machines. However, I can run test.py successfully.  I'm wondering is there any path problems? (I have torch, lua, luarocks installed)

**Comment by yujiali** [comment]
Looks like your torch could not find the package "class".  You should check if you are able to do require 'class' successfully.
