### ISSUE TITLE
How to use both node annotation and node labels?

### ISSUE THREAD

**Issue by jenniferSun27** [yujiali/ggnn#4]
Hi,
I noticed in the propagation model in the paper you used node annotations as initial node representations, while it seems that node labels are not used then. What if I'd like to use information in node labels and also want to mark some nodes as special?

Thank you very much.

**Comment by yujiali** [comment]
Hi,

These two - the node annotations and node labels, were used interchangeably.  Node labels or annotations, whatever you call it, they are properties associated with the nodes, so really no difference.  In the paper we fed in these node properties to initialize their states, but we can also have them be fed in each round of propagation, if that helps anything.
